--접속자 확인
SELECT USER FROM DUAL;

--계정 생성
DROP USER COMPANY_PROJECT CASCADE;
CREATE USER COMPANY_PROJECT IDENTIFIED BY rootroot;

--계정 확인
SELECT *
  FROM DBA_USERS 
 WHERE USERNAME = 'COMPANY_PROJECT';
 
--권한 부여
GRANT CONNECT, RESOURCE, CREATE SYNONYM, CREATE VIEW
   TO COMPANY_PROJECT;