--현재 DB를 사용하는 사용자명 출력
SELECT USER FROM DUAL;

--사용자 생성하기
DROP USER COMPANY_PROJECT CASCADE;
CREATE USER COMPANY_PROJECT IDENTIFIED BY rootroot;

--사용자 확인
SELECT *
  FROM DBA_USERS 
 WHERE USERNAME = 'COMPANY_PROJECT';
 
--Grant 명령으로 접속, 사용 권한 주기
GRANT CONNECT, RESOURCE, CREATE SYNONYM, CREATE VIEW
   TO COMPANY_PROJECT;