-- MEMBER TABLE 생성
CREATE TABLE member(
	name varchar2(10),
	userid varchar2(10),
	pwd varchar2(10),
	email varchar2(20),
	phone char(13),
	admin number(1) default 0,
	joindate date default sysdate,
	PRIMARY KEY (userid)
);

-- 접속한 계정의 테이블 정보 조회
SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'MEMBER';
-- 접속한 계정의 테이블별 컬럼 조회
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEMBER';
-- 접속한 계정의 테이블별 제약조건 검색
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ('MEMBER');

-- TITLE
DROP TABLE TITLE;
CREATE TABLE TITLE(
	TITLE_NO	 NUMBER PRIMARY KEY,
	TITLE_NAME	 VARCHAR2(40)
);
--COLUMN명 변경
--ALTER TABLE TITLE RENAME COLUMN TITLR_NAME TO TITLE_NAME;

-- DEPARTMENT
DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT(
	DEPT_NO		 NUMBER PRIMARY KEY,
	DEPT_NAME	 VARCHAR2(40),
	FLOOR 		 NUMBER
);

-- EMPLOYEE
DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE(
	EMP_NO 		NUMBER,
	EMP_NAME 	VARCHAR2(20) NOT NULL,
	TNO			NUMBER,
	MANAGER		NUMBER,
	SALARY		NUMBER,
	DNO			NUMBER,
	EMAIL		VARCHAR2(60) NOT NULL,
	PASSWD		VARCHAR2(60) NOT NULL,
	REGDATE		DATE DEFAULT SYSDATE,
	TEL			CHAR(13),
	PIC_URI		VARCHAR2(100),
	CONSTRAINT EMPLOYEE_EMPNO_PK	PRIMARY KEY (EMP_NO),
	CONSTRAINT EMPLOYEE_TNO_FK		FOREIGN KEY (TNO)		REFERENCES TITLE(TITLE_NO) ON DELETE SET NULL,
	CONSTRAINT EMPLOYEE_MANAGER_FK	FOREIGN KEY (MANAGER)	REFERENCES EMPLOYEE(EMP_NO),
	CONSTRAINT EMPLOYEE_SALARY_CK	CHECK (SALARY < 6000000),
	CONSTRAINT EMPLOYEE_DNO_FK		FOREIGN KEY (DNO)		REFERENCES DEPARTMENT(DEPT_NO) ON DELETE CASCADE
);

-- 제약 조건의 확인
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ('TITLE', 'DEPARTMENT', 'EMPLOYEE');

--EMPLOYEE VIEW CREATING, SELECT, DROP
CREATE OR REPLACE VIEW VM_EMPLOYEE_JOIN AS
SELECT E.EMP_NO , E.EMP_NAME , E.TNO , E.MANAGER , E.SALARY , E.DNO , E.EMAIL , E.TEL , E.REGDATE , E.PIC_URI,
	   T.TITLE_NAME , D.DEPT_NAME , M.EMP_NAME MANAGER_NAME
  FROM EMPLOYEE E JOIN TITLE T ON E.TNO = T.TITLE_NO
		LEFT JOIN EMPLOYEE M ON E.MANAGER = M.EMP_NO 
		JOIN DEPARTMENT D ON E.DNO = D.DEPT_NO;
		
SELECT EMP_NO , EMP_NAME , TNO , MANAGER , SALARY , DNO , EMAIL , TEL , REGDATE , PIC_URI,
	   TITLE_NAME , DEPT_NAME , MANAGER_NAME
  FROM VM_EMPLOYEE_JOIN;
 
DROP VIEW VM_EMPLOYEE_JOIN;