--Title-----------------------------------------------------------
SELECT TITLE_NO, TITLE_NAME FROM TITLE;
SELECT TITLE_NO, TITLE_NAME FROM TITLE WHERE TITLE_NO=1;
SELECT MAX(TITLE_NO)+1 FROM TITLE;
INSERT INTO TITLE(TITLE_NO, TITLE_NAME) VALUES (6, '계약직');
UPDATE TITLE SET TITLE_NAME = '정규직' WHERE TITLE_NO = 6;
DELETE FROM TITLE WHERE TITLE_NO=6;

--Department------------------------------------------------------
SELECT DEPT_NO,DEPT_NAME,FLOOR FROM DEPARTMENT;
SELECT DEPT_NO,DEPT_NAME,FLOOR FROM DEPARTMENT WHERE DEPT_NO=1;
INSERT INTO DEPARTMENT(DEPT_NO,DEPT_NAME,FLOOR) VALUES (5, '영양', 10);
UPDATE DEPARTMENT SET DEPT_NAME = '급식', FLOOR = 20 WHERE DEPT_NO = 5;
DELETE FROM DEPARTMENT WHERE DEPT_NO = 5;
SELECT MAX(DEPT_NO)+1 FROM DEPARTMENT;

--Employee--------------------------------------------------------
SELECT EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD, REGDATE, TEL, PIC_URI FROM EMPLOYEE;
SELECT EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD, REGDATE, TEL, PIC_URI FROM EMPLOYEE
 WHERE EMP_NO = 3011;
INSERT INTO EMPLOYEE (EMP_NO, EMP_NAME, TNO, MANAGER, SALARY, DNO, EMAIL, PASSWD, REGDATE, TEL, PIC_URI)
VALUES (1541, '콜렉트', 3, 4377, 999999, 2, 'collect@test.co.kr', '1234', sysdate, '010-123-1234', null);
UPDATE EMPLOYEE SET EMP_NAME = '최수정', TNO = 1, SALARY = 123456, PASSWD = '4321' WHERE EMP_NO = 1541;
DELETE FROM EMPLOYEE WHERE EMP_NO = 1541;

-----
CREATE OR REPLACE VIEW VM_EMPLOYEE_JOIN AS
SELECT E.EMP_NO , E.EMP_NAME , E.TNO , E.MANAGER , E.SALARY , E.DNO , E.EMAIL , E.TEL , E.REGDATE , E.PIC_URI,
	   T.TITLE_NAME , D.DEPT_NAME , M.EMP_NAME MANAGER_NAME
  FROM EMPLOYEE E JOIN TITLE T ON E.TNO = T.TITLE_NO
		LEFT JOIN EMPLOYEE M ON E.MANAGER = M.EMP_NO 
		JOIN DEPARTMENT D ON E.DNO = D.DEPT_NO;
       
SELECT EMP_NO , EMP_NAME , TNO , MANAGER , SALARY , DNO , EMAIL , TEL , REGDATE , PIC_URI,
	   TITLE_NAME , DEPT_NAME , MANAGER_NAME
  FROM VM_EMPLOYEE_JOIN;
 
SELECT EMP_NO , EMP_NAME , TNO , MANAGER , SALARY , DNO , EMAIL , TEL , REGDATE , PIC_URI,
	   TITLE_NAME , DEPT_NAME , MANAGER_NAME
  FROM VM_EMPLOYEE_JOIN
 WHERE EMP_NO = 1541;

DROP VIEW VM_EMPLOYEE_JOIN;