--Title-----------------------------------------------------------
SELECT TITLE_NO, TITLE_NAME FROM TITLE;
SELECT TITLE_NO, TITLE_NAME FROM TITLE WHERE TITLE_NO=1;
SELECT MAX(TITLE_NO)+1 FROM TITLE;
INSERT INTO TITLE(TITLE_NO, TITLE_NAME) VALUES (6, '계약직');
UPDATE TITLE SET TITLE_NAME = '정규직' WHERE TITLE_NO = 6;
DELETE FROM TITLE WHERE TITLE_NO=6;

--Department------------------------------------------------------
SELECT DEPT_NO,DEPT_NAME,FLOOR FROM DEPARTMENT;
SELECT DEPT_NO,DEPT_NAME,FLOOR FROM DEPARTMENT WHERE DEPT_NO=1;
INSERT INTO DEPARTMENT(DEPT_NO,DEPT_NAME,FLOOR) VALUES (5, '영양', 10);
UPDATE DEPARTMENT SET DEPT_NAME = '급식', FLOOR = 20 WHERE DEPT_NO = 5;
DELETE FROM DEPARTMENT WHERE DEPT_NO = 5;
SELECT MAX(DEPT_NO)+1 FROM DEPARTMENT;

--Employee--------------------------------------------------------